workflows:
  ios-workflow:
    name: Build iOS Daara App
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      node: 22 # ✅ Mis à jour de 20 à 22
      xcode: latest
    scripts:
      - name: Install Dependencies
        script: |
          cd daara-web
          npm install --legacy-peer-deps 
      - name: Web Build
        script: |
          cd daara-web
          npm run build
      - name: Capacitor Sync
        script: |
          cd daara-web
          npx cap sync ios
      - name: Build iOS (.ipa)
        script: | 
          cd daara-web
          # Compilation du projet Xcode
          xcode-project build-ipa --workspace ios/App/App.xcworkspace --scheme App
    artifacts:
      - daara-web/build/ios/ipa/*.ipa
      - daara-web/ios/App/build/ios/ipa/*.ipa