workflows:
  ios-workflow:
    name: Build iOS Daara App (Validation)
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      node: 22
      xcode: latest
    scripts:
      - name: Install Dependencies
        script: |
          cd daara-web
          npm install --legacy-peer-deps 
      - name: Web Build
        script: |
          cd daara-web
          npm run build
      - name: Capacitor Sync
        script: |
          cd daara-web
          npx cap sync ios
      - name: Build iOS (Validation Simulateur)
        script: | 
          cd daara-web/ios/App
          # On compile pour simulateur (pas besoin de signature ni de compte Apple)
          xcodebuild -project App.xcodeproj -scheme App -configuration Debug -sdk iphonesimulator
    artifacts:
      - daara-web/ios/App/build/iphonesimulator/*.app