workflows:
  ios-workflow:
    name: Build iOS Daara App (Modern SPM)
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      node: 22
      xcode: latest
    scripts:
      - name: Install Dependencies
        script: |
          cd daara-web
          npm install --legacy-peer-deps 
      - name: Web Build
        script: |
          cd daara-web
          npm run build
      - name: Capacitor Sync
        script: |
          cd daara-web
          # On nettoie l'ancien dossier ios pour repartir sur une base SPM propre
          rm -rf ios
          npx cap add ios
          npx cap sync ios
      - name: Build iOS (Validation Simulateur)
        script: | 
          cd daara-web/ios/App
          # En mode SPM, Xcode gère tout via le .xcodeproj
          xcodebuild -project App.xcodeproj -scheme App -configuration Debug -sdk iphonesimulator | xcpretty
    artifacts:
      - daara-web/ios/App/build/iphonesimulator/*.app